package Modelo;
// Generated 06-nov-2018 0:00:54 by Hibernate Tools 4.3.1



/**
 * Reserva generated by hbm2java
 */
public class Reserva  implements java.io.Serializable {


     private long codReserva;
     private Tours tours;
     private Turista turista;

    public Reserva() {
    }

    public Reserva(long codReserva, Tours tours, Turista turista) {
       this.codReserva = codReserva;
       this.tours = tours;
       this.turista = turista;
    }
   
    public long getCodReserva() {
        return this.codReserva;
    }
    
    public void setCodReserva(long codReserva) {
        this.codReserva = codReserva;
    }
    public Tours getTours() {
        return this.tours;
    }
    
    public void setTours(Tours tours) {
        this.tours = tours;
    }
    public Turista getTurista() {
        return this.turista;
    }
    
    public void setTurista(Turista turista) {
        this.turista = turista;
    }




}


