package Modelo;
// Generated 05-nov-2018 23:55:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Tours generated by hbm2java
 */
public class Tours  implements java.io.Serializable {


     private int codTour;
     private Guia guia;
     private String ciudad;
     private String idioma;
     private Integer duracion;
     private BigDecimal valoracion;
     private String descripcionTour;
     private String descripcionGuia;
     private String puntoEncuentro;
     private Set reservas = new HashSet(0);

    public Tours() {
    }

	
    public Tours(int codTour, Guia guia) {
        this.codTour = codTour;
        this.guia = guia;
    }
    public Tours(int codTour, Guia guia, String ciudad, String idioma, Integer duracion, BigDecimal valoracion, String descripcionTour, String descripcionGuia, String puntoEncuentro, Set reservas) {
       this.codTour = codTour;
       this.guia = guia;
       this.ciudad = ciudad;
       this.idioma = idioma;
       this.duracion = duracion;
       this.valoracion = valoracion;
       this.descripcionTour = descripcionTour;
       this.descripcionGuia = descripcionGuia;
       this.puntoEncuentro = puntoEncuentro;
       this.reservas = reservas;
    }
   
    public int getCodTour() {
        return this.codTour;
    }
    
    public void setCodTour(int codTour) {
        this.codTour = codTour;
    }
    public Guia getGuia() {
        return this.guia;
    }
    
    public void setGuia(Guia guia) {
        this.guia = guia;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getIdioma() {
        return this.idioma;
    }
    
    public void setIdioma(String idioma) {
        this.idioma = idioma;
    }
    public Integer getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(Integer duracion) {
        this.duracion = duracion;
    }
    public BigDecimal getValoracion() {
        return this.valoracion;
    }
    
    public void setValoracion(BigDecimal valoracion) {
        this.valoracion = valoracion;
    }
    public String getDescripcionTour() {
        return this.descripcionTour;
    }
    
    public void setDescripcionTour(String descripcionTour) {
        this.descripcionTour = descripcionTour;
    }
    public String getDescripcionGuia() {
        return this.descripcionGuia;
    }
    
    public void setDescripcionGuia(String descripcionGuia) {
        this.descripcionGuia = descripcionGuia;
    }
    public String getPuntoEncuentro() {
        return this.puntoEncuentro;
    }
    
    public void setPuntoEncuentro(String puntoEncuentro) {
        this.puntoEncuentro = puntoEncuentro;
    }
    public Set getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set reservas) {
        this.reservas = reservas;
    }




}


